name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: build
        run: |
          pip3 install pip west
          west init -m https://github.com/gl-inet/gl-nrf-sdk --mr v2.2.0-glinet gl-nrf-sdk
          cd gl-nrf-sdk/
          west update
          west zephyr-export

          nrf/scripts/bootstrap.sh
          export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
          export GNUARMEMB_TOOLCHAIN_PATH=$PWD/gcc-arm-none-eabi-9-2019-q4-major

          cd glinet/gl-dev-board-over-thread
          west build -b gl_nrf52840_dev_board

