name: release
on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - id: get-version
        uses: battila7/get-version-action@v2

      - uses: actions/checkout@v2
        with:
          submodules: true

      - id: release-asset
        run: |
          pip3 install pip west
          west init -m https://github.com/gl-inet/gl-nrf-sdk --mr v2.2.0-glinet gl-nrf-sdk
          cd gl-nrf-sdk/
          west update
          west zephyr-export

          nrf/scripts/bootstrap.sh
          export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
          export GNUARMEMB_TOOLCHAIN_PATH=$PWD/gcc-arm-none-eabi-9-2019-q4-major

          cd glinet/gl-dev-board-over-thread
          west build -b gl_thread_dev_board
          cp build/zephyr/app_update.bin ../
          cp build/zephyr/zephyr.bin ../

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          files: |
            release/1.1.9/GL-Thread-Dev-Board-MTD-OTA-v1.1.9.bin
            release/1.1.9/GL-Thread-Dev-Board-FTD-OTA-v1.1.9.bin
            app_update.bin
            zephyr.bin