name: release
on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - id: get-version
        uses: battila7/get-version-action@v2

      - uses: actions/checkout@v2
        with:
          submodules: true

      - id: release-asset
        run: |
          pip3 install pip west
          west init -m https://github.com/gl-inet/gl-nrf-sdk --mr v2.2.0-glinet gl-nrf-sdk
          cd gl-nrf-sdk/
          west update
          west zephyr-export

          nrf/scripts/bootstrap.sh
          export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
          export GNUARMEMB_TOOLCHAIN_PATH=$PWD/gcc-arm-none-eabi-9-2019-q4-major

          cd glinet/gl-dev-board-over-thread
          echo "Build $GITHUB_REF_NAME"
          sed -i "/CONFIG_MCUBOOT_IMAGE_VERSION/c\CONFIG_MCUBOOT_IMAGE_VERSION=\"${GITHUB_REF_NAME#*v}\"" prj.conf
          sed -i "/CONFIG_SW_VERSION/c\CONFIG_SW_VERSION=\"${GITHUB_REF_NAME#*v}\"" prj.conf
          echo "Build FTD"
          sed -i '/CONFIG_OPENTHREAD_FTD=n/c\CONFIG_OPENTHREAD_FTD=y' prj.conf
          sed -i '/CONFIG_OPENTHREAD_MTD=y/c\CONFIG_OPENTHREAD_MTD=n' prj.conf
          west build -b gl_nrf52840_dev_board
          cp build/zephyr/app_update.bin ../../../GL-Dev-Board-Thread-FTD-OTA-$GITHUB_REF_NAME.bin
          cp build/zephyr/merged.hex ../../../GL-Dev-Board-Thread-FTD-JLINK-UPGRADE-$GITHUB_REF_NAME.hex

          echo "Build MTD"
          sed -i '/CONFIG_OPENTHREAD_FTD=y/c\CONFIG_OPENTHREAD_FTD=n' prj.conf
          sed -i '/CONFIG_OPENTHREAD_MTD=n/c\CONFIG_OPENTHREAD_MTD=y' prj.conf
          west build -b gl_nrf52840_dev_board
          cp build/zephyr/app_update.bin ../../../GL-Dev-Board-Thread-MTD-OTA-$GITHUB_REF_NAME.bin
          cp build/zephyr/merged.hex ../../../GL-Dev-Board-Thread-MTD-JLINK-UPGRADE-$GITHUB_REF_NAME.hex

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          files: |
            GL-Dev-Board*.bin
            GL-Dev-Board*.hex
